name: meyochat
description: A reactive chat application fueled by a Firebase Firestore.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: 0.17.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
